name: "Build and run tests"

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main
    
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install dependencies
      run: dotnet restore RenderEngine
      
    - name: Build
      run: dotnet build RenderEngine --configuration Release --no-restore
    
    - name: Test
      run: dotnet test RenderEngine --no-restore --verbosity normal

  
